title: Lesson Mapper
description: Visual Mind Mapping Tools and Templates for Teachers
theme: just-the-docs
baseurl: "" # the subpath of your site, e.g. /blog
permalink: pretty

# GitHub repo metadata for "Edit this page" links
repository: ExMapo/lesson-mapper
gh_edit_repository: https://github.com/ExMapo/lesson-mapper
gh_edit_branch: main
gh_edit_view_mode: tree

# Enable features
search_enabled: true
enable_copy_code_button: true
nav_enabled: true
heading_anchors: true
color_scheme: light
back_to_top: true
back_to_top_text: "Back to top"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Sidebar navigation setup
nav:
  - title: "Home"
    url: "/"
  - title: "Subjects"
    children:
      - title: "Math"
        url: /docs/math
      - title: "Science"
        url: /docs/science
      - title: "English"
        url: /docs/english

# Footer
footer_content: 'Copyright &copy; 2024 ExMapo. Powered by <a href="https://pages.github.com/">GitHub Pages</a> and <a href="https://just-the-docs.github.io/">Just the Docs</a>.'

# Optional plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

# External links in top right
aux_links:
  "View on GitHub":
    - "https://github.com/ExMapo/lesson-mapper"
aux_links_new_tab: true

# Kramdown settings for markdown rendering
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
